source 'https://github.com/CocoaPods/Specs.git'

target 'UHNBLEController', :exclusive => true do
  pod "UHNBLEController", :path => "../"
  pod 'UHNDebug', :git => "git@github.ehealthinnovation.org:PHIT/UHNDebug.git"
end

target 'Tests', :exclusive => true do
  pod "UHNBLEController", :path => "../"

  pod 'Specta', :git => 'https://github.com/specta/specta.git', :tag => 'v0.3.0.beta1'
  pod 'Expecta'
  pod 'OCMockito', '~> 1.0'
end
